title: <p align="center"> Ramandeep Mehra </p>
logo: /assets/img/Photo.jpg
description: 
  <p align="center">
  <a href="Ramandeep Mehra (Data Scientist).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ramandeepmehra/">LinkedIn</a> |
  <a href="https://github.com/Ramandeepmehra">GitHub</a>

  <br>   
Tech Analyst with a strong foundation in data science and a proven track record of success at Cognizant, Accenture and Aegis.

Expertise in deploying ML models, optimizing business processes, and improving customer satisfaction through advanced analytics. 
  <br>
  </p>




theme: jekyll-theme-minimal
