title: <p align="center"> Ramandeep Mehra </p>
logo: /assets/img/Photo.jpg
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ramandeepmehra/">LinkedIn</a> |
  <a href="https://github.com/Ramandeepmehra">GitHub</a>

  <br>   
Tech Analyst with a strong foundation in 
data science life cycle and a proven track 
record of success at Cognizant, Accenture and Aegis.

  <br>
  </p>




theme: jekyll-theme-minimal
