title: <p align="center"> Ramandeep Mehra </p>
logo: /assets/img/Photo.png

description:
  <p align="center">
  <a href= "https://drive.google.com/drive/u/0/folders/1gfnLCbzIN_C3CH0BI15mWKqfL3qu-Bsw">Resume</a> |
  <a href="https://www.linkedin.com/in/ramandeepmehra/">LinkedIn</a> |
  <a href="https://github.com/Ramandeepmehra">GitHub</a>
  
  <br>   
  
Results-driven Tech Analyst (6+ years) with expertise in developing and deploying ML models (NLP, Generative AI), optimizing BI, and delivering advanced analytics.  
Experience at Cognizant, Accenture, and Aegis.
  <br>
  </p>



theme: jekyll-theme-minimal
