title: <p align="center"> Ramandeep Mehra </p>
logo: /assets/img/Photo.png

description:
  <p align="center">
  <a href= /assets/img/Ramandeep Mehra (Data Scientist).pdf>Resume</a> |
  <a href="https://www.linkedin.com/in/ramandeepmehra/">LinkedIn</a> |
  <a href="https://github.com/Ramandeepmehra">GitHub</a>
  
  <br>   

  Tech Analyst at Cognizant.
  Proficient in deploying ML models, advanced analytics, and optimizing business intelligence. 
  I've 6+ years of experience. Worked with Congnizant, Accenture and Aegis.  
  <br>
  </p>



theme: jekyll-theme-minimal
